### ISSUE TITLE
Document how to configure advanced rocksdb parameters

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#12095]
Document how to configure nested parameters in `columnFamilyOptions`. 

For example, it is not clear how to configure advanced configurations such as [BlockBasedTableFactory parameters](https://github.com/camunda/zeebe/blob/main/zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java#L245) via broker configuration. They can be configured them as follows.
```
zeebe:
  broker: 
    experimental:
      rocksdb:
        columnFamilyOptions:
           table_factory: "{block_size=1234; pin_top_level_index_and_filter=false;pin_l0_filter_and_index_blocks_in_cache=true}"
```
More details: [slack discussion](https://camunda.slack.com/archives/C037RS2JHB8/p1678439287853719?thread_ts=1678374725.751079&cid=C037RS2JHB8)

Typically, users are not expected to override rocksdb config. However, it would still be good to document this since we allow to override columnFamily options. At the very least, it will help us test different configurations easily without changing the code.
