### ISSUE TITLE
zbctl/Zeebe Go-Client overwrites cached credentials for a different audience

### ISSUE THREAD

**Issue by megglos** [camunda/camunda#12960]
**Describe the bug**

As reported by @jonathanlukas and confirmed by @ingorichtsmeier [in Slack](https://camunda.slack.com/archives/CSQ2E3BT4/p1685538176335879), the usage of the java client and zbctl on the same host leads to zbctl purging oauth credentials of the audience used by the other client.

```
No cache-file existis:
Starting Java client: cache-file OK
Invoking zbctl: cache-file broken

Other way around, no cache-file given:
invoking zbctl: cache-file OK
starting java-client: cache-file OK
invoking zbctl: cache-file broken
```

This seems to be an incompatibility of both clients, I spotted that:
- the **java client used the full zeebe address as key** to store credentials, the **go client only the audience**
- the records are serialised differently, e.g. the java quotes the accessToken, the go client not

**To Reproduce**

1. Setup oauth credentials for zeebe
2. Use the java client locally with credentials and credential cache enabled (default)
3. use zbctl
4. observe partially cleared credentials of the java client cache entry (only expiry remains)

When using the java client to authenticate with the audience `zeebe.camunda.io` the cache file may look like this:
```
---
e9.bru-2.zeebe.camunda.io:
  auth:
    credentials:
      accessToken: "ey...6w"
      tokenType: "Bearer"
      expiry: "2023-06-01T13:26:27.993877+02:00"
```

Then using zbctl results in the following state:
```
e9760cb8-7d48-4d10-b163-039e26835aac.bru-2.zeebe.camunda.io:
  auth:
    credentials:
      accesstoken: ""
      tokentype: ""
      refreshtoken: ""
      expiry: 2023-06-01T13:26:27.993877+02:00
zeebe.camunda.io:
  auth:
    credentials:
      accesstoken: ey...bg
      tokentype: Bearer
      refreshtoken: ""
      expiry: 2023-06-01T12:23:28.502134+02:00
```

**Expected behavior**

Both clients can be used on the same host without side-effects on the other.
One of:
- both clients either reuse cached credentials of another client
- both clients use isolated cache files

**Environment:**
- OS: any
- Zeebe Version: 8.2.x (likely all supported versions)
