### ISSUE TITLE
Handle journal segment flush errors

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#14866]
**Describe the bug**

We currently do not recover properly from flush/fsync errors when flushing the journal. One main issue is on the leader, where we commit asynchronously from the appends whenever we have quorum. At that point we don't have necessarily the entries buffered, and we cannot trust what's in the page cache.

Here is @lenaschoenburg and I's proposal, which we would need to prototype first:

For all other cases we would need to start buffering the appends. @lenaschoenburg and I discussed a possible solution which we would like to prototype. It would serve as a first step towards moving us off of memory mapped files, and thus having more control over our I/O behavior, more observability, and better support for a wider range of file systems (incl. network file systems).

For any guaranteed flushed data, we just keep the current approach - read from the memory mapped buffer/page cache. But when you append something, we'll write it to the memory mapped buffer AND also in a in-memory buffer we own. If a reader wants to read past what has been flushed, it will always read from the in-memory buffer, not from the page cache. Once data is guaranteed flushed, it's evicted from the in-memory buffer, and readers can read from the page cache.

When flushing fails, we can simply write back what's in memory and flush again.

There's obviously some complexity involved here:

- We need bounded buffers to avoid memory exhaustion
- This means we need to deal with write stalls/back pressure in the append pipeline
- When flushing occurs, readers must be moved from the in-memory buffer to the page cache, which may not be optimal.

This is not a quick fix, but it would be good to prototype this as soon as possible to get an idea of value/effort ratio.

**To Reproduce**

Trigger an error during the flush. You can use `strace` for example to inject a `fsync` error.

**Expected behavior**

Flushing is safe to retry by rewriting the whole un-flushed entries.

**Comment by panagiotisgts** [comment]
Gave a try to [LazyFS](https://github.com/dsrhaslab/lazyfs) for reproducing File System failures. There is [this](https://www.vldb.org/pvldb/vol17/p3017-ramos.pdf) published paper regarding the creation of LazyFS and also what they have uncovered by testing known large scale systems against a failing File system.

Dependencies to build this and use on CI are not uncommon in standard Linux distribution images. Time to build and use this library consists of, on my machine: 
- Building of bundled libpcache - 26s
- Building of actual lazyfs - 9.5s

One of the pros of LazyFS is it's configuration which can be predetermined, via `.toml` files to reproduce certain scenarios reliably and consistently by defining the injection of specific errors on the FS bound to specific files, you can use regex as well. 

fex: 
``` toml
[[injection]]
type = "torn-op"
file = "/home/pgoutis/Documents/lazyfs/lazyfs.root/raft-partition/partitions/1/raft-partition-partition-1-1.log" 
parts = 4                      
persist = [2]                
occurrence = 1          
[[injection]]
type="torn-seq"
op="write"
file="/home/pgoutis/Documents/lazyfs/lazyfs.root/raft-partition/partitions/1/raft-partition-partition-1-1.log"
persist=[1,4]
occurrence=2
```

Another thing I've found useful is the inclusion of extensive syscall logs for file ops, where they can give you additional hints on how the underlying kernels handles the file ops requested, by enabling the flag,

```toml
[filesystem]
log_all_operations=true
```

The only downside I've seen so far is the limitation of most FUSE3 based file systems of not implementing all syscalls necessarily as expected, with the blocker for us being the `getattrs` command reporting 0B of disk space available of the FUSE3 directory. To bypass this, I had to disable all disk space checks that we do on the brokers in order for the broker to start up.
