### ISSUE TITLE
Partition remains unhealthy even after deleting the data

### ISSUE THREAD

**Issue by michaelholtermann** [camunda/camunda#17682]
This is a follow-up of #16955.

As discussed over there, we
1. paused all broker's nodes
2. created a backup by snapshotting the underlying EBS volumes 
3. unpaused all nodes (not we have the same situation as before, 1 partition on 1 node is unhealthy)
4. deleted the partition's data `rm -rf data/raft-partition/partitions/3`
5. killed the pod with the broken partition in Kubernetes

Then we can see:
1. the broken Pod get's terminated by K8s
2. the remaining Broker nodes stays alive
3. the former broken Pod get's restarted
4. the former broken Pod become alive

So all seems fine.

But:
- after roughly half a minute, partition 3 on **another node** become unhealthy.

So the problem persists and is able to move to another node.

We tried this process a second time with the newly brokened node. After that, the error moves back to the first broken pod.

So I think this problem has nothing to do with a broken file system.

**Idea**
We run 3 nodes with 3 partitions each.

On this installation, only 2 partitions have a Leader; partition 3 does not have a leader somewhere. I don't know if each partition need a leader, somewhere. But if, maybe there is an issue with becoming a LEADER node for this partition?

**To Reproduce**
Unknown, see #16955.

**Expected behavior**
The partition or node is able to recover from the other nodes.

**Environment:**
- OS: Linux, Kubernetes, Stateful Set backed by AWS EBS gp2 volumes
- Zeebe Version: 8.4.5
- Configuration: 
```
            - name: ZEEBE_BROKER_CLUSTER_CLUSTERNAME
              value: "process-control-tower-zeebe"
            - name: ZEEBE_GATEWAY_CONTACT_POINT
              value: "process-control-tower-gateway-service"
            - name: ZEEBE_LOG_LEVEL
              value: "warn"
            - name: ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT
              value: "3"
            - name: ZEEBE_BROKER_CLUSTER_CLUSTERSIZE
              value: "3"
            - name: ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR
              value: "3"
            - name: ZEEBE_BROKER_THREADS_CPUTHREADCOUNT
              value: "2"
            - name: ZEEBE_BROKER_THREADS_IOTHREADCOUNT
              value: "2"
            - name: ZEEBE_BROKER_GATEWAY_ENABLE
              value: "false"
            - name: ZEEBE_BROKER_EXPORTERS_HAZELCAST_JARPATH
              value: exporters/zeebe-hazelcast-exporter.jar
            - name: ZEEBE_BROKER_EXPORTERS_HAZELCAST_CLASSNAME
              value: io.zeebe.hazelcast.exporter.HazelcastExporter
            - name: ZEEBE_BROKER_NETWORK_COMMANDAPI_PORT
              value: "26501"
            - name: ZEEBE_BROKER_NETWORK_INTERNALAPI_PORT
              value: "26502"
            - name: ZEEBE_BROKER_NETWORK_MONITORINGAPI_PORT
              value: "9600"
            - name: ZEEBE_BROKER_DATA_DISK_FREE_SPACE_REPLICATION
              value: "1408MB" # default 1024MB. See https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/disk-space/
            - name: ZEEBE_BROKER_DATA_DISK_FREE_SPACE_PROCESSING # default 2048MB
              value: "2048MB" # default 2048MB. See https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/disk-space/
            - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
              value: "true" # export
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JAVA_TOOL_OPTIONS
              # align the max heap should be ca 80% of max mem of the container
              value: "-Xmx3500M -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/zeebe/data -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log -XX:+ExitOnOutOfMemoryError"
```

[logs-from-process-control-tower-broker-in-process-control-tower-broker-0 (2).log](https://github.com/camunda/zeebe/files/15076335/logs-from-process-control-tower-broker-in-process-control-tower-broker-0.2.log)
