### ISSUE TITLE
Exporter command updateLastExportedRecordPosition() seems to have no effect

### ISSUE THREAD

**Issue by MeAndMyTeam** [camunda/camunda#20586]
As you can read in https://forum.camunda.io/t/zeebe-keeps-replying-records-to-custom-exporter/49272 we break our problem down in a single exporter, which calls the updateLastExportedRecordPosition() to save the current position. A log of the position before this code row gives us
```
zeebe_exportertest      | 2024-07-29 10:38:24.403 [Broker-0] [zb-fs-workers-1] [Exporter-1] INFO
zeebe_exportertest      |       fm.zeebe.exporter.ZeebeExporter - Position:71
```
in the log file.
I also try to set the ZEEBE_BROKER_DATA_SNAPSHOTPERIOD to 1 minuten. After 1 minuten i see this in the log file.
```
zeebe_exportertest      | 2024-07-29 10:39:03.966 [Broker-0] [zb-fs-workers-1] [SnapshotStore-1] DEBUG
zeebe_exportertest      |       io.camunda.zeebe.logstreams.snapshot - Taking temporary snapshot into /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/26-1-56-42.
zeebe_exportertest      | 2024-07-29 10:39:04.072 [Broker-0] [zb-fs-workers-0] [SnapshotStore-1] INFO
zeebe_exportertest      |       io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore - Committed new snapshot 26-1-56-42
zeebe_exportertest      | 2024-07-29 10:39:04.108 [Broker-0] [zb-fs-workers-1] [SnapshotStore-4] DEBUG
zeebe_exportertest      |       io.camunda.zeebe.logstreams.snapshot - Taking temporary snapshot into /usr/local/zeebe/data/raft-partition/partitions/4/snapshots/3-1-4-5.
zeebe_exportertest      | 2024-07-29 10:39:04.204 [Broker-0] [zb-fs-workers-0] [SnapshotStore-4] INFO
zeebe_exportertest      |       io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore - Committed new snapshot 3-1-4-5
zeebe_exportertest      | 2024-07-29 10:39:04.398 [Broker-0] [zb-fs-workers-1] [SnapshotStore-5] DEBUG
zeebe_exportertest      |       io.camunda.zeebe.logstreams.snapshot - Taking temporary snapshot into /usr/local/zeebe/data/raft-partition/partitions/5/snapshots/3-1-4-5.
zeebe_exportertest      | 2024-07-29 10:39:04.497 [Broker-0] [zb-fs-workers-1] [SnapshotStore-5] INFO
zeebe_exportertest      |       io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore - Committed new snapshot 3-1-4-5
zeebe_exportertest      | 2024-07-29 10:39:08.520 [Broker-0] [zb-fs-workers-0] [SnapshotStore-6] DEBUG
zeebe_exportertest      |       io.camunda.zeebe.logstreams.snapshot - Taking temporary snapshot into /usr/local/zeebe/data/raft-partition/partitions/6/snapshots/3-1-4-5.
zeebe_exportertest      | 2024-07-29 10:39:08.612 [Broker-0] [zb-fs-workers-1] [SnapshotStore-6] INFO
zeebe_exportertest      |       io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore - Committed new snapshot 3-1-4-5
zeebe_exportertest      | 2024-07-29 10:39:08.725 [Broker-0] [zb-fs-workers-0] [SnapshotStore-2] DEBUG
zeebe_exportertest      |       io.camunda.zeebe.logstreams.snapshot - Taking temporary snapshot into /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/3-1-4-5.
zeebe_exportertest      | 2024-07-29 10:39:08.728 [Broker-0] [zb-fs-workers-1] [SnapshotStore-3] DEBUG
zeebe_exportertest      |       io.camunda.zeebe.logstreams.snapshot - Taking temporary snapshot into /usr/local/zeebe/data/raft-partition/partitions/3/snapshots/3-1-4-5.
zeebe_exportertest      | 2024-07-29 10:39:08.833 [Broker-0] [zb-fs-workers-0] [SnapshotStore-2] INFO
zeebe_exportertest      |       io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore - Committed new snapshot 3-1-4-5
zeebe_exportertest      | 2024-07-29 10:39:08.847 [Broker-0] [zb-fs-workers-1] [SnapshotStore-3] INFO
zeebe_exportertest      |       io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore - Committed new snapshot 3-1-4-5
```
Everthing seems to be saved correctly.

Also after another minuten he logs this
```
zeebe_exportertest      | 2024-07-29 10:40:04.073 [Broker-0] [zb-actors-0] [SnapshotDirector-1] DEBUG
zeebe_exportertest      |       io.camunda.zeebe.logstreams.snapshot - Did not take a snapshot. Previous snapshot was taken for the same processed position 56 and exported position 42.
zeebe_exportertest      | 2024-07-29 10:40:04.330 [Broker-0] [zb-actors-1] [SnapshotDirector-4] DEBUG
zeebe_exportertest      |       io.camunda.zeebe.logstreams.snapshot - Did not take a snapshot. Previous snapshot was taken for the same processed position 4 and exported position 5.
zeebe_exportertest      | 2024-07-29 10:40:04.728 [Broker-0] [zb-actors-1] [SnapshotDirector-5] DEBUG
zeebe_exportertest      |       io.camunda.zeebe.logstreams.snapshot - Did not take a snapshot. Previous snapshot was taken for the same processed position 4 and exported position 5.
zeebe_exportertest      | 2024-07-29 10:40:08.811 [Broker-0] [zb-actors-1] [SnapshotDirector-6] DEBUG
zeebe_exportertest      |       io.camunda.zeebe.logstreams.snapshot - Did not take a snapshot. Previous snapshot was taken for the same processed position 4 and exported position 5.
kafka-ui_exportertest   | 2024-07-29 10:40:08,857 DEBUG [parallel-2] c.p.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: local
kafka-ui_exportertest   | 2024-07-29 10:40:08,869 DEBUG [parallel-5] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: local
zeebe_exportertest      | 2024-07-29 10:40:08.950 [Broker-0] [zb-actors-1] [SnapshotDirector-2] DEBUG
zeebe_exportertest      |       io.camunda.zeebe.logstreams.snapshot - Did not take a snapshot. Previous snapshot was taken for the same processed position 4 and exported position 5.
zeebe_exportertest      | 2024-07-29 10:40:08.954 [Broker-0] [zb-actors-1] [SnapshotDirector-3] DEBUG
zeebe_exportertest      |       io.camunda.zeebe.logstreams.snapshot - Did not take a snapshot. Previous snapshot was taken for the same processed position 4 and exported position 5.
```
which i interpret with "nothing more to do, we saved all positions". Weird, that he logs "processed position 56 and exported position 42" while we are a position 71.

But when i stopped my container and restart them, zeebe just called our exporter again with the "old" positions, beginning from 43.

```
zeebe_exportertest      | 2024-07-29 10:58:00.297 [Broker-0] [zb-fs-workers-1] [Exporter-1] INFO
zeebe_exportertest      |       fm.zeebe.exporter.ZeebeExporter - Position:43
[...]
zeebe_exportertest      | 2024-07-29 10:58:00.513 [Broker-0] [zb-fs-workers-1] [Exporter-1] INFO
zeebe_exportertest      |       fm.zeebe.exporter.ZeebeExporter - Position:71
```

This is my compose file

```
services:

  zeebe:
    container_name: zeebe_exportertest
    image: camunda/zeebe:${CAMUNDA_PLATFORM_VERSION:-8.5.5}
    environment:
      - ZEEBE_BROKER_CLUSTER_NODEID=0
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=6
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=1
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=1
      - ZEEBE_LOG_LEVEL=DEBUG
      - ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED=true
      - ZEEBE_BROKER_EXPORTERS_KAFKA_JARPATH=/usr/local/zeebe/lib/zeebe-exporter.jar
      - ZEEBE_BROKER_EXPORTERS_KAFKA_CLASSNAME=fm.zeebe.exporter.ZeebeExporter
      - ZEEBE_BROKER_DATA_SNAPSHOTPERIOD=1m
      - ZEEBE_BROKER_DATA_LOGSEGMENTSIZE = 128MB
      - ZEEBE_BROKER_DATA_DIRECTORY=data

    ports:
      - "26500:26500"
      - "9600:9600"
    volumes:
      #- zeebe_exportertest:/usr/local/zeebe/data
      - ./zeebe_data:/usr/local/zeebe/data
      - ./build/libs/zeebe-exporter.jar:/usr/local/zeebe/lib/zeebe-exporter.jar

volumes:
  zeebe_exportertest:
    driver: local
  elastic_exportertest:
    driver: local
```

**Expected behavior**

The exporter shall not export the same positions again. With the current behaviour we got the effect, that the exporter get events from the last days after a restart.

**Log/Stacktrace**

see above

**Environment:**
- OS: docker compose
- Zeebe Version: 8.5.5
- Configuration: see above
