### ISSUE TITLE
Enable Write Limits in the benchmarks

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/camunda#21324]
In order to also visualize flow control-related metrics in the benchmarks we need to enable the write limits in the benchmark clusters.

- [x] Decide the write limits for the benchmarks
- [x] Enable the write limits in the benchmarks https://github.com/zeebe-io/benchmark-helm/pull/178
- [x] Find the right configuration for our medic benchmarks
- [x] Find the right configuration for our release benchmarks
- [x] Decide if we should we enable it on the latency benchmarks as well?
- [x] Create a new Helm release https://github.com/zeebe-io/benchmark-helm/pull/180
- [x] Validate that new benchmarks have the configuration

**Comment by rodrigo-lourenco-lopes** [comment]
Having deployed several uncontrolled model loops in one of our standard benchmarks, the maximum processing per partition I observed was around 3.8k. 

Since we don't want to limit the processing of the benchmark partitions with the write limits, I propose a high limit value of 4000. The reason to not use one limit much higher and be on the safer side, is so that the load cluster, and partition load metrics that are dependent on the write limit to present realistic values, since they display the current rate / write limit.

For the remaining metrics I propose the same as the one for the medium size cluster, except having the throttling disabled.
Therefore they should be for the standard cluster:

```
zeebe: 
  broker:
    flowControl:
      write:
        enabled: true
        rampUp: 0
        limit: 4000
        throttling:
          enabled: false
          acceptableBacklog: 200000
          minimumLimit: 500
          resolution: 15s
```
