### ISSUE TITLE
Remove id property from user creation REST request

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda#21673]
<h2>Description</h2>

Currently when creating a user the reques takes an id. This id doesn't exist at this point. It won't be used either so we can remove it from this request.

Current:

```yaml
    UserWithPasswordRequest:
      type: "object"
      properties:
        password:
          type: "string"
        id:
          type: "integer"
          format: "int64"
        username:
          type: "string"
        name:
          type: "string"
        email:
          type: "string"
```
