### ISSUE TITLE
C8 API Variable value as free-form object

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#23724]
### Description

Currently the value of a variable is a JSON object encoded and stored as String value.

Example: 
```json
{
 "name": "person"
 "value" : "{\"name\":  \"Homer\"}"
}
```

The value should be an JSON object:

```json
{
 "name": "person"
 "value" : {"name":  "Homer"}
}
```

It is called `Free-Form Object` in [OpenAPI](https://swagger.io/docs/specification/v3_0/data-models/data-types/#objects)

The value can be used in search filter and for result items:

VariableFilter:
```
    VariableFilterRequest:
      description: Variable filter request.
      type: object
      properties:
        variableKey:
          description: The key for this variable.
          type: integer
          format: int64
       ...
        value:
          description: The value of the variable.
          type: object
```

VariableItem:
```yaml
    VariableItem:
      description: Variable search response item.
      type: object
      properties:
        variableKey:
        ...
        value:
          description: Value of this variable.
          type: object
```

### TODO

- [ ] How handle this internally in API. Storage in datastore is currently as string. Can this be stored as an object?
- [ ] How to implement this and where. In service layer or conversion in controller?
- [ ] Implement as result item
- [ ] Implement as filter

### Additional Information

Raised in [Slack thread](https://camunda.slack.com/archives/C06UKS51QV9/p1728977700713929)
