### ISSUE TITLE
Identity Secret not handled in Identity environment variable

### ISSUE THREAD

**Issue by hisImminence** [camunda/camunda#25904]
# Description

We got a report that after upgrading the Helm Charts from 11.0.1 to 11.0.4 an error is thrown indicating: "Please supply a valid client secret for Identity".

The environment variable `CAMUNDA_IDENTITY_CLIENT_SECRET` in the configmap](https://github.com/camunda/camunda-platform-helm/blob/e6d2cb660960f6a2815b9045fb14b7613d2e7884/charts/camunda-platform-8.6/templates/identity/configmap.yaml#L221) was changed and it seems identity does not handle it correctly.

As a workaround; set the env var in addition to the old one, e.g.:
```
env:
  - name: IDENTITY_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: camunda-platform
        key: identity-secret 
  - name: CAMUNDA_IDENTITY_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: camunda-platform
        key: identity-secret  
```

### Related support tickets
* [SUPPORT-24716](https://jira.camunda.com/browse/SUPPORT-24716?focusedCommentId=383391&atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258Y29tbWVudA%3D%3D)
* [SUPPORT-24944](https://jira.camunda.com/browse/SUPPORT-24944)
