### ISSUE TITLE
Change the type of the property `state` from `string` to enum in `ProcessInstance`/`ProcessInstanceFilter` 

### ISSUE THREAD

**Issue by saig0** [camunda/camunda#26779]
**Description**

In the Camunda Java client, the property `state` in the `ProcessInstance` search response object and the `ProcessInstanceFilter` has the type `string`. 

We should change the type to an enum that represents the possible process instance states and is aligned with the OpenAPI specification [rest-api.yaml](https://github.com/camunda/camunda/blob/main/zeebe/gateway-protocol/src/main/proto/rest-api.yaml#L4919-L4924). 

```
ProcessInstanceStateEnum:
      description: The state, one of ACTIVE, COMPLETED, CANCELED.
      enum:
        - ACTIVE
        - COMPLETED
        - CANCELED
```

Related to https://github.com/camunda/camunda/issues/21836
Related to https://github.com/camunda/camunda/issues/20660
Similar to https://github.com/camunda/camunda/issues/25908
