### ISSUE TITLE
Backport StandaloneSchemaManager to 8.6/.7

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda#27883]
BAckport the Schema Manager from https://github.com/camunda/camunda/issues/25922 to 8.6
Because of architecture streamlining, the code is different in 8.6. 
I pushed code that works on 8.6.8 on this branch: https://github.com/camunda/camunda/compare/8.6.8...25922-standalone-schema-manager-8.6.8

Todo
- [x] Merge for 8.6.9
- [x] Push to 8.7 branch to avoid a gap there (in 8.8.alpha1 it is included via #25922 already)

Usage:

Run the `schema.bat`/`schema.sh` and provide an `application.yaml`, I tested with:

```yaml
# Zeebe Standalone Broker configuration file (with embedded gateway)

# This file is based on broker.standalone.yaml.template but stripped down to contain only a limited
# set of configuration options. These are a good starting point to get to know Zeebe.
# For advanced configuration options, have a look at the templates in this folder.

# !!! Note that this configuration is not suitable for running a standalone gateway. !!!
# If you want to run a standalone gateway node, please have a look at gateway.yaml.template

# ----------------------------------------------------
# Byte sizes
# For buffers and others must be specified as strings and follow the following
# format: "10U" where U (unit) must be replaced with KB = Kilobytes, MB = Megabytes or GB = Gigabytes.
# If unit is omitted then the default unit is simply bytes.
# Example:
# sendBufferSize = "16MB" (creates a buffer of 16 Megabytes)
#
# Time units
# Timeouts, intervals, and the likes, must be specified either in the standard ISO-8601 format used
# by java.time.Duration, or as strings with the following format: "VU", where:
#   - V is a numerical value (e.g. 1, 5, 10, etc.)
#   - U is the unit, one of: ms = Millis, s = Seconds, m = Minutes, or h = Hours
#
# Paths:
# Relative paths are resolved relative to the installation directory of the broker.
# ----------------------------------------------------

zeebe:
  broker:
    gateway:
      # Enable the embedded gateway to start on broker startup.
      # This setting can also be overridden using the environment variable ZEEBE_BROKER_GATEWAY_ENABLE.
      enable: true

      network:
        # Sets the port the embedded gateway binds to.
        # This setting can also be overridden using the environment variable ZEEBE_BROKER_GATEWAY_NETWORK_PORT.
        port: 26500

      security:
        # Enables TLS authentication between clients and the gateway
        # This setting can also be overridden using the environment variable ZEEBE_BROKER_GATEWAY_SECURITY_ENABLED.
        enabled: false
        authentication:
          # Controls which authentication mode is active, supported modes are 'none' and 'identity'.
          # If 'identity' is set, authentication will be done using camunda-identity, which needs to
          # be configured in the corresponding subsection. See also https://docs.camunda.io/docs/self-managed/identity/what-is-identity/ .
          # This setting can also be overridden using the environment variable ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_MODE.
          mode: none

    data:
      # Specify a directory in which data is stored.
      # This setting can also be overridden using the environment variable ZEEBE_BROKER_DATA_DIRECTORY.
      directory: data
      # The size of data log segment files.
      # This setting can also be overridden using the environment variable ZEEBE_BROKER_DATA_LOGSEGMENTSIZE.
      logSegmentSize: 128MB
      # How often we take snapshots of streams (time unit)
      # This setting can also be overridden using the environment variable ZEEBE_BROKER_DATA_SNAPSHOTPERIOD.
      snapshotPeriod: 15m

    cluster:
      # Specifies the Zeebe cluster size.
      # This can also be overridden using the environment variable ZEEBE_BROKER_CLUSTER_CLUSTERSIZE.
      clusterSize: 1
      # Controls the replication factor, which defines the count of replicas per partition.
      # This can also be overridden using the environment variable ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR.
      replicationFactor: 1
      # Controls the number of partitions, which should exist in the cluster.
      # This can also be overridden using the environment variable ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT.
      partitionsCount: 1

    threads:
      # Controls the number of non-blocking CPU threads to be used.
      # WARNING: You should never specify a value that is larger than the number of physical cores
      # available. Good practice is to leave 1-2 cores for ioThreads and the operating
      # system (it has to run somewhere). For example, when running Zeebe on a machine
      # which has 4 cores, a good value would be 2.
      # This setting can also be overridden using the environment variable ZEEBE_BROKER_THREADS_CPUTHREADCOUNT
      cpuThreadCount: 2
      # Controls the number of io threads to be used.
      # This setting can also be overridden using the environment variable ZEEBE_BROKER_THREADS_IOTHREADCOUNT
      ioThreadCount: 2

camunda:
  database:
    # Controls which database must be used, possible values: elasticsearch, opensearch
    # This setting can also be overridden using the environment variable CAMUNDA_DATABASE_TYPE
    type: elasticsearch
    # Sets the name of the cluster, default name is "elasticsearch"
    # This setting can also be overridden using the environment variable CAMUNDA_DATABASE_CLUSTERNAME
    clusterName: elasticsearch
    # Sets the database url.
    # This setting can also be overridden using the environment variable CAMUNDA_DATABASE_URL
    url: https://localhost:9200
  # Operate configuration properties
  operate:
    # Set operate username and password.
    # If user with <username> does not exists it will be created.
    # Default: demo/demo
    #username:
    #password:
    # ELS instance to store Operate data
    elasticsearch:
      # Cluster name
      clusterName: elasticsearch
      # URL
      url: https://localhost:9200
      prefix: operate
      username: camunda-admin
      password: camunda123
      ssl:
        selfSigned: true
        verifyHostname: false
        certificatePath: C:/Users/ruecker/Downloads/elasticsearch-8.14.0-windows-x86_64/elasticsearch-8.14.0/config/certs/http_ca.crt
    # Zeebe instance
    zeebe:
      # Gateway address
      gatewayAddress: localhost:26500
    # ELS instance to export Zeebe data to
    zeebeElasticsearch:
      # Cluster name
      clusterName: elasticsearch
      # URL
      url: https://localhost:9200
      # Index prefix, configured in Zeebe Elasticsearch exporter
      prefix: zeebe-record
      username: camunda-admin
      password: camunda123
      ssl:
        selfSigned: true
        verifyHostname: false
        certificatePath: C:/Users/ruecker/Downloads/elasticsearch-8.14.0-windows-x86_64/elasticsearch-8.14.0/config/certs/http_ca.crt
  # Tasklist configuration properties
  tasklist:
    # Set Tasklist username and password.
    # If user with <username> does not exists it will be created.
    # Default: demo/demo
    #username:
    #password:
    # ELS instance to store Tasklist data
    elasticsearch:
      # Cluster name
      clusterName: elasticsearch
      # URL
      url: https://localhost:9200
      prefix: tasklist
      username: camunda-admin
      password: camunda123
      ssl:
        selfSigned: true
        verifyHostname: false
        certificatePath: C:/Users/ruecker/Downloads/elasticsearch-8.14.0-windows-x86_64/elasticsearch-8.14.0/config/certs/http_ca.crt
    # Zeebe instance
    zeebe:
      # Gateway address
      gatewayAddress: localhost:26500
    # ELS instance to export Zeebe data to
    zeebeElasticsearch:
      # Cluster name
      clusterName: elasticsearch
      # Url
      url: https://localhost:9200
      # Index prefix, configured in Zeebe Elasticsearch exporter
      prefix: zeebe-record
      username: camunda-admin
      password: camunda123
      ssl:
        selfSigned: true
        verifyHostname: false
        certificatePath: C:/Users/ruecker/Downloads/elasticsearch-8.14.0-windows-x86_64/elasticsearch-8.14.0/config/certs/http_ca.crt
```

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/28460
- [ ] https://github.com/camunda/camunda/pull/28345
- [ ] https://github.com/camunda/camunda-docs/pull/5114
- [ ] https://github.com/camunda/camunda-docs/pull/5101
- [ ] https://github.com/camunda/camunda/pull/28987
```
