### ISSUE TITLE
Helm chart allows deploying Connectors with Basic auth enabled on the API

### ISSUE THREAD

**Issue by megglos** [camunda/camunda#28664]
With https://github.com/camunda/camunda/issues/27439 support of basic auth was added to the Helm chart. However, adapting connectors to support basic auth on the Zeebe gateway was not included in the scope and needs to be followed up on. Until then Connectors usage will only be possible when disabling authorizations and authentication on the API, effectively limiting it to the usage to the following values.

```
  security:
    authentication:
      method: basic
      unprotectedApi: true
    authorizations:
      enabled: false
```

Acceptance Criteria:
- [x] When `authentication.method: basic`, the connector needs to be setup with some default basic credentials
