### ISSUE TITLE
OpenAPI Spec misses type for some enums

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda#30674]
The OpenAPI Spec misses the type for some of the enums, for example
https://github.com/camunda/camunda-docs/blob/main/api/camunda/camunda-openapi.yaml#L5369

```yaml
    PermissionTypeEnum:
      description: Specifies the type of permissions.
      enum:
        - ACCESS
```

should be

```yaml
    PermissionTypeEnum:
      description: Specifies the type of permissions.
      type: string
      enum:
        - ACCESS
```

Without the type attribute it is not rendered properly in the Swagger UI.

Or is there a specific reason behind not having the type in those places?
