### ISSUE TITLE
identity UI doesn't consider context path.

### ISSUE THREAD

**Issue by maryarm** [camunda/camunda#31956]
### 

### Description
Slack conv: https://camunda.slack.com/archives/C06UYJMMETZ/p1749030282043789

When using the local helm chart or any how set the context path for the application, identity UI doesn't consider it and always assume the url as the root. 

<img width="1328" alt="Image" src="https://github.com/user-attachments/assets/5b5877dc-826a-4ece-bd34-a12f5d872b83" />

### Motivation

Have a fix for it so it's could be possible to access identity UI.

### Acceptance criteria

- [ ] When the context path is set, identity login works.

**Comment by hamza-m-masood** [comment]
@maryarm 
@OmranAbazid 
I would like this issue to be opened again because this bug still persists on 8.8.0-alpha5

To reproduce, please use the following values.yaml:
```yaml
global:
  secrets:
    autoGenerated: false
    name: "integration-test-credentials"
  ingress:
    enabled: true
    className: nginx
    # The Ingress host will be added via CLI.
    host: "hamzatest-basic.ci.distro.ultrawombat.com"
    tls:
      enabled: true
      # A wildcard certificate will be used.
      secretName: camunda-platform
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "{{ .Values.global.ingress.host }}"
      external-dns.alpha.kubernetes.io/ttl: "60"
  identity:
    auth:
      enabled: false
  security:
    authentication:
      method: basic

identity:
  enabled: false

identityKeycloak:
  enabled: false

optimize:
  enabled: false
  contextPath: "/optimize"

connectors:
  contextPath: "/connectors"

webModeler:
  enabled: false
  contextPath: "/modeler"
  image:
    pullSecrets:
      - name: index-docker-io
      - name: registry-camunda-cloud
  restapi:
    mail:
      # This value is required, otherwise the restapi pod wouldn't start.
      fromAddress: noreply@example.com

# WebModeler Database.
webModelerPostgresql:
  enabled: false
  auth:
    existingSecret: "integration-test-credentials"
    secretKeys:
      adminPasswordKey: "webmodeler-postgresql-admin-password"
      userPasswordKey: "webmodeler-postgresql-user-password"

core:
  enabled: true
  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  contextPath: "/core"
  env:
    - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
      value: none
  ingress:
    grpc:
      enabled: true
      className: nginx
      host: "grpc-{{ .Values.global.ingress.host }}"
      tls:
        enabled: true
        # A wildcard certificate will be used.
        secretName: camunda-platform-zeebe-gateway
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "core-{{ .Values.global.ingress.host }}"
        external-dns.alpha.kubernetes.io/ttl: "60"

console:
  enabled: false
  contextPath: "/"
  image:
    pullSecrets:
      - name: index-docker-io
      - name: registry-camunda-cloud

elasticsearch:
  maxUnavailable: 0
  master:
    replicaCount: 1

prometheusServiceMonitor:
  enabled: false
  labels:
    release: kube-prometheus-stack

```
