### ISSUE TITLE
When Optimize is configured to use SSL with Elasticsearch, custom headers are not added

### ISSUE THREAD

**Issue by matthewBearCamunda** [camunda/camunda#32240]
### Component

Optimize

### Affected version

8.6, 8.7, 8.8

### Severity

High

### Likelihood

High

### Description

When Optimize is configured to use SSL with Elasticsearch custom headers are not being added from plugins

### Steps to reproduce

1. Configure Optimize to use a custom plugin. Have this plugin log to the console on load and when adding a header
2. Configure Optimize to use SSL with Elasticsearch
3. Configure Elasticsearch to accept SSL
- See below comments on how to properly set all this up 
5. Start Optimize
6. Wait for the first elasticsearch call

### Current behavior

When looking at the logs, the method that adds headers to ES calls is not printed to the logs. The method is not called

### Expected behavior

When looking at the logs, messages from the plugin are present

### Environment

SaaS & SM

### Version

- Component Version: 8.6.6

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

https://jira.camunda.com/browse/SUPPORT-26923

**Comment by matthewBearCamunda** [comment]
To create a key and cert, execute the following commands. The two files will be created in the current directory

- `openssl req -new -x509 -nodes -sha256 -days 365 -key host.key -out host.cert`
- `keytool -import -alias testalias -file host.cert -keypass pass123 -keystore test.jks -storepass pass123`

**Comment by matthewBearCamunda** [comment]
Use the following settings to set up Optimize and Elasticsearch in docker to use SSL

Please make sure to enter the correct paths for the key, cert, plugin jar, and jks file

 ```
 optimize:
    profiles: ["", "elasticsearch"]
    container_name: optimize
    image: camunda/optimize:SNAPSHOT
    depends_on:
      - elasticsearch
      - identity
    volumes:
      - type: bind
        source: jarpath goes here
        target: /usr/local/plugin.jar
      - type: bind
        source: key path goes here
        target: /usr/local/host.key
      - type: bind
        source: cert path goes here
        target: /usr/local/host.cert
      - type: bind
        source: jks path goes here
        target: /usr/local/test.jks
    ports:
      - "8090:8090"
      - "8092:8092"
    environment:
      - SPRING_PROFILES_ACTIVE=platform
      - CAMUNDA_OPTIMIZE_IDENTITY_ISSUER_URL=http://localhost:18080/auth/realms/camunda-platform
      - CAMUNDA_OPTIMIZE_IDENTITY_ISSUER_BACKEND_URL=http://keycloak:8080/auth/realms/camunda-platform
      - CAMUNDA_OPTIMIZE_IDENTITY_BASE_URL=http://identity:8081/
      - CAMUNDA_OPTIMIZE_IDENTITY_CLIENTID=optimize
      - CAMUNDA_OPTIMIZE_IDENTITY_CLIENTSECRET=XALaRPl5qwTEItdwCMiPS62nVpKs7dL7
      - CAMUNDA_OPTIMIZE_IDENTITY_AUDIENCE=optimize-api
      - OPTIMIZE_ELASTICSEARCH_HOST=elasticsearch
      - OPTIMIZE_ELASTICSEARCH_HTTP_PORT=9200
      - CAMUNDA_OPTIMIZE_SECURITY_AUTH_COOKIE_SAME_SITE_ENABLED=false
      - CAMUNDA_OPTIMIZE_ENTERPRISE=false
      - CAMUNDA_OPTIMIZE_ZEEBE_ENABLED=true
      - CAMUNDA_OPTIMIZE_ZEEBE_NAME=zeebe-record
      - CAMUNDA_OPTIMIZE_ZEEBE_PARTITION_COUNT=2
      - CAMUNDA_OPTIMIZE_IMPORT_DATA_SKIP_DATA_AFTER_NESTED_DOC_LIMIT_REACHED=true
      # This should only be set if you plan to use JWTs for the public API rather than a statically configured token
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/auth/realms/camunda-platform/protocol/openid-connect/certs
      - OPTIMIZE_LOG_LEVEL=DEBUG
      - CAMUNDA_OPTIMIZE_ELASTICSEARCH_INTERCEPTORPLUGINS_0_ID=my-plugin
      - CAMUNDA_OPTIMIZE_ELASTICSEARCH_INTERCEPTORPLUGINS_0_CLASSNAME=org.test.example
      - CAMUNDA_OPTIMIZE_ELASTICSEARCH_INTERCEPTORPLUGINS_0_JARPATH=/usr/local/plugin.jar
      - JAVA_TOOL_OPTIONS=-XX:UseSVE=0
      - CAMUNDA_OPTIMIZE_ELASTICSEARCH_SSL_ENABLED=true
      - CAMUNDA_OPTIMIZE_ELASTICSEARCH_SECURITY_SSL_CERTIFICATE=/usr/local/host.cert
      - CAMUNDA_OPTIMIZE_ELASTICSEARCH_SECURITY_SSL_SELF_SIGNED=true
      - CAMUNDA_OPTIMIZE_ELASTICSEARCH_SECURITY_SSL_CERTIFICATE_AUTHORITIES=['/usr/local/host.cert']
      - OPTIMIZE_JAVA_OPTS=-Xmx2G -Djavax.net.ssl.keyStore=/usr/local/test.jks -Djavax.net.ssl.trustStore=/usr/local/test.jks -Djavax.net.ssl.keyStorePassword=pass123 -Djavax.net.ssl.trustStorePassword=pass123 -Djavax.net.ssl.trustStoreType=jks
      - CAMUNDA_OPTIMIZE_ELASTICSEARCH_SECURITY_USERNAME=elastic
      - CAMUNDA_OPTIMIZE_ELASTICSEARCH_SECURITY_PASSWORD=changeme
    networks:
      - optimize
      - identity-network

  elasticsearch:
    profiles: ["", "elasticsearch"]
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION:-8.13.0}
    volumes:
      - type: bind
        source: /Users/matt/tmp/host.key
        target: /usr/share/elasticsearch/config/host.key
      - type: bind
        source: /Users/matt/tmp/host.cert
        target: /usr/share/elasticsearch/config/host.cert
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - action.destructive_requires_name=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g -XX:UseSVE=0
      - CLI_JAVA_OPTS=-XX:UseSVE=0
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/host.key
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/host.cert
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/host.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/host.cert
      - ELASTIC_PASSWORD=changeme
      - ELASTICSEARCH_USERNAME=elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    cpu_count: 4
    mem_limit: 2g
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cat/health | grep -q green" ]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - optimize
```
