### ISSUE TITLE
Cannot start process or perform actions on userTasks on tasklist service started on V2

### ISSUE THREAD

**Issue by esraagamal6** [camunda/camunda#32384]
### 

### 

### 

### 

### Description

When starting tasklist service on `8.8.0-snapshot` with V2 APIs via docker file, i cannot start process, assign/unassign or complete userTasks

### Steps to reproduce

1. Pull main branch of camunda repo
2. Update tasklist service inisde the [docker-compose file](https://github.com/camunda/camunda/blob/main/tasklist/config/docker-compose.yml) inside  [tasklist/config](https://github.com/camunda/camunda/tree/main/tasklist/config)
```
      - SPRING_PROFILES_ACTIVE=dev,consolidated-auth
      - CAMUNDA_TASKLIST_ZEEBE_COMPATIBILITY_ENABLED=true
      - CAMUNDA_TASKLIST_V2_MODE_ENABLED=true
```
4. Open Terminal in [tasklist/config folder](https://github.com/camunda/camunda/tree/main/tasklist/config)
5. Run `DATABASE=elasticsearch docker compose up -d tasklist`
6. Deploy a process
7. Navigate to tasklist and start the process

### Current behavior

Process could not be started
```
{
  "type" : "about:blank",
  "title" : "java.net.ConnectException",
  "status" : 503,
  "detail" : "Expected to handle REST API request, but there was a connection error with one of the brokers",
  "instance" : "/v2/process-instances"
}
```

### Expected behavior

- User can start process
- User can interact with userTasks

### Environment

SM

### Version

- Component Version: 8.8.0-SNAPSHOT with V2 API

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links
https://github.com/camunda/product-hub/issues/2516

**Comment by esraagamal6** [comment]
🔕  I was able to start it only via camunda standalone
```
  camunda:
    container_name: camunda
    image: camunda/camunda:8.8.0-alpha5-rc1
    environment:
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx1g"
      - ZEEBE_BROKER_NETWORK_HOST=camunda
      - SPRING_PROFILES_ACTIVE=consolidated-auth,tasklist,broker,operate,identity,dev-data
      - CAMUNDA_SECURITY_AUTHENTICATION_UNPROTECTEDAPI=false
      - CAMUNDA_SECURITY_AUTHORIZATIONS_ENABLED=true
      - CAMUNDA_SECURITY_AUTHENTICATION_METHOD=BASIC
      - CAMUNDA_SECURITY_MULTITENANCY_ENABLED=true
      - CAMUNDA_SECURITY_INITIALIZATION_DEFAULTROLES_ADMIN_USERS_0=demo
      - CAMUNDA_TASKLIST_V2_MODE_ENABLED=true
    ports:
      - 26500:26500
      - 9600:9600
      - 8080:8080
    depends_on:
      - ${DATABASE}
    networks:
      - zeebe_network
    env_file:
      - envs/.env.database.${DATABASE}
```
