### ISSUE TITLE
Intermitteny empty line logs

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda#32665]
### 

### 

### 

### 

### Description

A customer reported intermittent empty line logs when they enabled stackdriver. Example:

```
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"lambda$proceedWithTransition$1","file":"PartitionTransitionProcess.java","line":91},"message":"Transition to FOLLOWER on term 22 - transitioning SnapshotDirector","serviceContext":{"service":"}","version":"}"},"context":{"threadId":20,"partitionId":"3","actor-scheduler":"Broker-0","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.system","threadName":"zb-actors-2","actor-name":"ZeebePartition-3"},"timestampSeconds":1747981029,"timestampNanos":211379734}{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"lambda$proceedWithTransition$1","file":"PartitionTransitionProcess.java","line":91},"message":"Transition to FOLLOWER on term 22 - transitioning CommandApiService","serviceContext":{"service":"}","version":"}"},"context":{"threadId":18,"partitionId":"1","actor-scheduler":"Broker-0","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.system","threadName":"zb-actors-0","actor-name":"ZeebePartition-1"},"timestampSeconds":1747981029,"timestampNanos":211849915}

{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"lambda$proceedWithTransition$1","file":"PartitionTransitionProcess.java","line":91},"message":"Transition to FOLLOWER on term 22 - transitioning SnapshotDirector","serviceContext":{"service":"}","version":"}"},"context":{"threadId":18,"partitionId":"1","actor-scheduler":"Broker-0","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.system","threadName":"zb-actors-0","actor-name":"ZeebePartition-1"},"timestampSeconds":1747981029,"timestampNanos":212389902}
```

The first line contains 2 logs. Then an empty line is logged and the next one contains a single log. It may be noteworthy that the logline with 2 logs contains a log for 2 different partitions. We've also observed 3 different logs on a single line (all different partition ids).

### Steps to reproduce

```
zeebe:
  enabled: true
  javaOpts: >-
    -Dspring.main.banner-mode=off
    -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005
  env:
    - name: ZEEBE_LOG_APPENDER
      value: "Stackdriver"
    - name: CAMUNDA_LOG_FILE_APPENDER_ENABLED
      value: "false"
  pvcSize: 10Gi
  clusterSize: 2 
  partitionCount: 2 
  replicationFactor: 2 
```

### Current behavior

Randomly an empty line is logged. Notably before this happens multiple logs are logged on a single line.

### Expected behavior

No empty lines are logged

### Environment

SM

### Version

- Component Version: 8.7.2

### Rootcause

Likely there is some concurrency issue going on. I looked at the `StackdriverLayout` and noticed we write a newline to the output seperate from the log entry. Maybe this has to do with it.

https://github.com/camunda/camunda/blob/3a7fb3ea18e07c09b57c1307ec005724dea24693/zeebe/util/src/main/java/io/camunda/zeebe/util/logging/StackdriverLayout.java#L108-L109

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

https://jira.camunda.com/browse/SUPPORT-27499
