### ISSUE TITLE
Review and adjust old identity configuration of Orchestration Cluster

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda#34143]
### 

### Description

Currently there is existing, old identity configuration in the default application.yaml as part of the Orchestration Cluster, e.g.

```
zeebe:
  broker:
    gateway:
      security:
        # Enables TLS authentication between clients and the gateway
        # This setting can also be overridden using the environment variable ZEEBE_BROKER_GATEWAY_SECURITY_ENABLED.
        enabled: false
        authentication:
          # Controls which authentication mode is active, supported modes are 'none' and 'identity'.
          # If 'identity' is set, authentication will be done using camunda-identity, which needs to
          # be configured in the corresponding subsection. See also https://docs.camunda.io/docs/self-managed/identity/what-is-identity/ .
          # This setting can also be overridden using the environment variable ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_MODE.
          mode: none
```

This should be reviewed and adjusted. Additionally, we should consider to add the new authentication and authorization defaults to make editing easy for users. Otherwise one has to search through documentation and find the right config.

### Motivation

Old configs are confusing for users / admins and might lead to unwanted sideeffects

### Acceptance criteria

- [ ] ...
