### ISSUE TITLE
Add configuration for Console Ping feature

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/camunda#34258]
Add the global configuration that enables every node to have access to the following information:

- enable/disable flag
- console url endpoint
- cluster unique ID (this initially should be configured explicitly)
- cluster name (human readable)
- costume properties map

The configuration should be set under `camunda.console` as discussed [here](https://camunda.slack.com/archives/C08R8SRTNUF/p1750681146908409). This feature is also disabled by default.

```
camunda:
  console:
    ping:
      enabled: true
      endpoint: https://123/etc 
      clusterId: 123 
      clusterName: myCLuster
      pingPeriod: 60
      properties:
```
