### ISSUE TITLE
Create a Spring Boot properties configuration for document stores

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda#34492]
Reference: https://camunda.slack.com/archives/C075A4LHPQD/p1749201282636169?thread_ts=1749132117.439899&cid=C075A4LHPQD

### 

### User Story

First of all, I can see that your code is designed to be flexible since the configuration is provided from an interface. This is cool, so backwards compatibility of configuration being done against 8.7 can be implemented.
Next, I would expect the configuration to be done in the spring-boot way. This means I have a set of properties that can be written to the application.yaml of camunda or the respective component and is picked up from there.
Moreover, Spring boot would allow a configuration via environment variables which would also cover the current configuration way.
From the properties structure, I can see that:
* there is 1 default document store (being set by name)
* there is a thread pool size
* there is a map (model is a list, but each record has an id that is unique) of document stores being configurable (name to configuration)
* each document store configuration contains (next to the id) a class of the provider + a set of properties that vary from impl to impl

### Design

These attributes of the configuration are pretty much the same as for the exporter, which would allow us to create a properties configuration in the spring boot way:
```yaml
camunda:
  document-store:
    default-store: aws
    thread-pool-size: 1
    stores:
      aws:
        provider-class: blablabla
        properties:
          foo: bar
      aws2:
        provider-class: blablabla2
        properties:
          foo: bar2
```

This properties structure is aligned with exporters. The names of the properties could still be adjusted (for example camunda.document-store.stores.<store-name>.properties could also be called camunda.document-store.stores.<store-name>.args to entirely align with [exporters](https://docs.camunda.io/docs/self-managed/zeebe-deployment/exporters/elasticsearch-exporter/#configuration)), but the idea matches pretty much + it would still be extensible + it would still be configurable via env

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):
